# Name of the action visible in the action overview
name: Transform tokens send from figma
image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:14-ubi8

stages:
    - build

.npmPrepare:
    before_script:
        - cd libs/designtokens
        - npm ci

build:
    # the name for the entire job
    name: Transform Figma design tokens for specific platforms
    stage: build
    #only:
        #- triggers
    extends: .npmPrepare
    script:
        - cat $TRIGGER_PAYLOAD
        - npm run clean # clear previous build
        - npm run transform-figma-tokens
        - echo 'Trying to create "tokens" directory...'
        - mkdir -p tokens
        - echo 'create json from request body'
        # this creates a json file from the stringified json from the request body
          # 'design-tokens.tokens.json'
          # it uses the json string that was send as the tokens parameter
          # dir: 'tokens'
               
        # We now create a pull request
          #commit-message: "Tokens updated"
          #title: "Design tokens updated"
          #body: "Design tokens have been updated via Figma and need to be reviewed."

